import Head from "next/head";
import SearchBar from "../components/SearchBar";
import Card from "../components/Card";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import favicon from "../public/favicon.ico";

export default function Home() {
    const [character, setCharacter] = useState({});

    return (
        <div className={styles.container}>
            <Head>
                <title>amiibo browser</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href={favicon.src} />
            </Head>

            <main className={styles.main}>
                <SearchBar
                    callBack={(data) => {
                        setCharacter(data);
                    }}
                />
                {character && character.hasOwnProperty("amiibo") ? (
                    <Card character={character} />
                ) : (
                    <div>
                        <h2>No results..</h2>
                    </div>
                )}
            </main>
        </div>
    );
}
